### ISSUE TITLE
2.8 Workspace Issues

### ISSUE THREAD

**Issue by rismay** [bitrise-steplib/steps-xcode-archive#185] opened 2020-04-24 04:03 UTC
## 2.7 Works
This command is run and everything works:
```
set -o pipefail && xcodebuild "-workspace" "/Users/vagrant/git/apple/Avalon.xcworkspace" "-scheme" "Trader" "-configuration" "Release" "COMPILER_INDEX_STORE_ENABLE=NO" "archive" "-archivePath" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__archive__868249701/Trader.xcarchive" | xcpretty
```
## 2.8 Fails 

Before that command is run this is displayed:
```
Failed to read project platform: /Users/vagrant/git/apple/Avalon.xcworkspace: failed to get SDKROOT: key: string("SDKROOT") not found in: serialized.Object(serialized.Object{"CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING":"YES", "CLANG_WARN_BOOL_CONVERSION":"YES", "CLANG_WARN_COMMA":"YES", "CLANG_WARN_CONSTANT_CONVERSION":"YES", "CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS":"YES", "CLANG_WARN_EMPTY_BODY":"YES", "CLANG_WARN_ENUM_CONVERSION":"YES", "CLANG_WARN_INFINITE_RECURSION":"YES", "CLANG_WARN_INT_CONVERSION":"YES", "CLANG_WARN_NON_LITERAL_NULL_CONVERSION":"YES", "CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF":"YES", "CLANG_WARN_OBJC_LITERAL_CONVERSION":"YES", "CLANG_WARN_RANGE_LOOP_ANALYSIS":"YES", "CLANG_WARN_STRICT_PROTOTYPES":"YES", "CLANG_WARN_SUSPICIOUS_MOVE":"YES", "CLANG_WARN_UNREACHABLE_CODE":"YES", "CLANG_WARN__DUPLICATE_METHOD_MATCH":"YES", "ENABLE_STRICT_OBJC_MSGSEND":"YES", "GCC_NO_COMMON_BLOCKS":"YES", "GCC_WARN_64_TO_32_BIT_CONVERSION":"YES", "GCC_WARN_ABOUT_RETURN_TYPE":"YES", "GCC_WARN_UNDECLARED_SELECTOR":"YES", "GCC_WARN_UNINITIALIZED_AUTOS":"YES", "GCC_WARN_UNUSED_FUNCTION":"YES", "GCC_WARN_UNUSED_VARIABLE":"YES"})
```

**Comment by natalia-osa** [comment] 2020-04-27 17:38
I have the same issue. A week ago it was working properly.

**Comment by csk4ta** [comment] 2020-04-29 19:47
Hello,

We are sorry to hear this! Our Tooling team is aware of this issue with the latest version of the step and is currently looking into this.
Could you please send us the .xcodeproj and .xcworkspace files? It would help us resolve the issue. If you don't want to attach the files here, you can email us at support@bitrise.io or submit a ticket [here](https://www.bitrise.io/bitrise-support).

Alternatively, other users are reporting that downgrading to step version 2.7 resolves the issue, so in the meantime, as a workaround, I would kindly suggest using this version. We'll update you here as soon as the issue is resolved. Thank you!

**Comment by omichde** [comment] 2020-05-13 12:03
Same issue, went back from 2.8.2 zu 2.7.x and now it works

**Comment by mefiblogger** [comment] 2020-05-13 15:02
Hi 👋 @rismay,

First of all, thank your for your patience! I have some good news: our team fixed the issue and I'd like to provide some context and details about it.

Since version  [2.8.0](https://github.com/bitrise-steplib/steps-xcode-archive/releases/tag/2.8.0), we add the `-destination` flag to the `xcodebuild` call, to make sure the step builds an iOS or tvOS project.

The root-cause was that the step built a macOS archive, which has slightly different file structure from an iOS archive.

This change also solves this issue partially: [#180 - Catalyst app can't be correctly parsed](https://github.com/bitrise-steplib/steps-xcode-archive/issues/180)

Version 2.8.0 parses the given project and determines the destination flag value, based on the `SDKROOT` build settings.

This new version introduced an issue, by the invalid expectation of having `SDKROOT` build settings as a project level build settings:

- https://github.com/bitrise-steplib/steps-xcode-archive/issues/184
- https://github.com/bitrise-steplib/steps-xcode-archive/issues/185.

In version [2.8.1](https://github.com/bitrise-steplib/steps-xcode-archive/releases/tag/2.8.1), we use the target build settings returned by `xcodebuild -showBuildSettings` to get the `SDKROOT` value.

**I close this issue as the latest release should fix it. If you need more info or help, just open a new issue or get in touch with our Support Team.**

Thanks and happy building 🚀 
Mefi

**Closed by mefiblogger** 2020-05-13 15:02 UTC
