### ISSUE TITLE
Please update to Xcode 7.3 or later to continue developing with your Apple ID.

### ISSUE THREAD

**Issue by talk812** [bitrise-steplib/steps-xcode-archive#287] opened 2022-03-22 09:30 UTC
When AutoCodeSigning 

failed to manage code signing: failed to ensure profiles: failed to find profile: failed to query Developer Portal: Apple provided the following error info:
Please update to Xcode 7.3 or later to continue developing with your Apple ID., stacktrace: /Users/[REDACTED]/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/client.rb:763:in `parse_response'
/Users/[REDACTED]/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/portal/portal_client.rb:669:in `provisioning_profiles_via_xcode_api'
/Users/[REDACTED]/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.193.1/spaceship/lib/spaceship/portal/provisioning_profile.rb:319:in `all'
/private/var/folders/ds/8lz3xw2s09jfp13nlv1tpgjc0000gn/T/1398877256/profiles.rb:21:in `list_profiles'
main.rb:46:in `<main>'

my Xcode Stack is already to Montery and the Xcode version is 13.3.x on MacOS 12.2
Why is "Please update to Xcode 7.3 or later to continue developing with your Apple ID" this?

**Comment by lpusok** [comment] 2022-03-22 13:56
Hello @talk812,
The cause seems to be an update in an Apple API which we use through _fastlane_. 
If you can use an API key to authenticate (not supported for Apple Enterprise accounts, that is non-App Store), that would work around this.
If you are continuing to use Apple ID to authenticate, can you please add a script Step with the following contents and report the result?
```
    - script:
        inputs:
        - content: |-
            set -ex
            envman add --key SPACESHIP_AVOID_XCODE_API --value "0"
```

We are checking if it can be fixed with a Step update.

References:
https://github.com/fastlane/fastlane/issues/20060

**Comment by talk812** [comment] 2022-03-23 02:29
After add the env SPACESHIP_AVOID_XCODE_API, now it works!   Thanks a lot.

**Comment by lpusok** [comment] 2022-03-23 07:10
@talk812,
Just curious, did the original issue happen consistently every time?

**Comment by talk812** [comment] 2022-03-23 07:11
yes,  before adding SPACESHIP_AVOID_XCODE_API, it failed every time

**Comment by ofalvai** [comment] 2022-04-14 15:31
The latest step version (4.2.3) fixes this issue, the workaround is no longer needed.

**Closed by ofalvai** 2022-04-14 15:31 UTC
